# Generated by Django 5.0.1 on 2024-01-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_tag_article_category_commentary_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
