# Generated by Django 5.0.1 on 2024-01-26 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_author_alter_commentary_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='article.commentary'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='top_level_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
